services:
  - type: web
    name: poetry-royal-belal206
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev --prefix api && npm ci --include=dev --prefix client && npm run build --prefix client
    startCommand: node api/index.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
